import React from 'react';
export const complianceDetails = () => <div>compliance distinct</div>;
export const compliance_detail_0 = (p:any)=> <div>compliance 0 ISO 55000</div>;
export const compliance_detail_1 = (p:any)=> <div>compliance 1 audit</div>;
export const compliance_detail_2 = (p:any)=> <div>compliance 2 traceability</div>;
export const compliance_detail_3 = (p:any)=> <div>compliance 3 ISO 55000</div>;
export const compliance_detail_4 = (p:any)=> <div>compliance 4 audit</div>;
export const compliance_detail_5 = (p:any)=> <div>compliance 5 traceability</div>;
export const compliance_detail_6 = (p:any)=> <div>compliance 6 ISO 55000</div>;
export const compliance_detail_7 = (p:any)=> <div>compliance 7 audit</div>;
export const compliance_detail_8 = (p:any)=> <div>compliance 8 traceability</div>;
export const compliance_detail_9 = (p:any)=> <div>compliance 9 ISO 55000</div>;
export const compliance_detail_10 = (p:any)=> <div>compliance 10 audit</div>;
export const compliance_detail_11 = (p:any)=> <div>compliance 11 traceability</div>;
export const compliance_detail_12 = (p:any)=> <div>compliance 12 ISO 55000</div>;
export const compliance_detail_13 = (p:any)=> <div>compliance 13 audit</div>;
export const compliance_detail_14 = (p:any)=> <div>compliance 14 traceability</div>;
export const compliance_detail_15 = (p:any)=> <div>compliance 15 ISO 55000</div>;
export const compliance_detail_16 = (p:any)=> <div>compliance 16 audit</div>;
export const compliance_detail_17 = (p:any)=> <div>compliance 17 traceability</div>;
export const compliance_detail_18 = (p:any)=> <div>compliance 18 ISO 55000</div>;
export const compliance_detail_19 = (p:any)=> <div>compliance 19 audit</div>;