import React from 'react';
export const anomaliesDetails = () => <div>anomalies distinct</div>;
export const anomalies_detail_0 = (p:any)=> <div>anomalies 0 threshold</div>;
export const anomalies_detail_1 = (p:any)=> <div>anomalies 1 isolation forest</div>;
export const anomalies_detail_2 = (p:any)=> <div>anomalies 2 SPC</div>;
export const anomalies_detail_3 = (p:any)=> <div>anomalies 3 z-score</div>;
export const anomalies_detail_4 = (p:any)=> <div>anomalies 4 threshold</div>;
export const anomalies_detail_5 = (p:any)=> <div>anomalies 5 isolation forest</div>;
export const anomalies_detail_6 = (p:any)=> <div>anomalies 6 SPC</div>;
export const anomalies_detail_7 = (p:any)=> <div>anomalies 7 z-score</div>;
export const anomalies_detail_8 = (p:any)=> <div>anomalies 8 threshold</div>;
export const anomalies_detail_9 = (p:any)=> <div>anomalies 9 isolation forest</div>;
export const anomalies_detail_10 = (p:any)=> <div>anomalies 10 SPC</div>;
export const anomalies_detail_11 = (p:any)=> <div>anomalies 11 z-score</div>;
export const anomalies_detail_12 = (p:any)=> <div>anomalies 12 threshold</div>;
export const anomalies_detail_13 = (p:any)=> <div>anomalies 13 isolation forest</div>;
export const anomalies_detail_14 = (p:any)=> <div>anomalies 14 SPC</div>;
export const anomalies_detail_15 = (p:any)=> <div>anomalies 15 z-score</div>;
export const anomalies_detail_16 = (p:any)=> <div>anomalies 16 threshold</div>;
export const anomalies_detail_17 = (p:any)=> <div>anomalies 17 isolation forest</div>;
export const anomalies_detail_18 = (p:any)=> <div>anomalies 18 SPC</div>;
export const anomalies_detail_19 = (p:any)=> <div>anomalies 19 z-score</div>;