import React from 'react';
export const maintenanceDetails = () => <div>maintenance distinct</div>;
export const maintenance_detail_0 = (p:any)=> <div>maintenance 0 work order</div>;
export const maintenance_detail_1 = (p:any)=> <div>maintenance 1 scheduling</div>;
export const maintenance_detail_2 = (p:any)=> <div>maintenance 2 spare parts</div>;
export const maintenance_detail_3 = (p:any)=> <div>maintenance 3 MRO</div>;
export const maintenance_detail_4 = (p:any)=> <div>maintenance 4 work order</div>;
export const maintenance_detail_5 = (p:any)=> <div>maintenance 5 scheduling</div>;
export const maintenance_detail_6 = (p:any)=> <div>maintenance 6 spare parts</div>;
export const maintenance_detail_7 = (p:any)=> <div>maintenance 7 MRO</div>;
export const maintenance_detail_8 = (p:any)=> <div>maintenance 8 work order</div>;
export const maintenance_detail_9 = (p:any)=> <div>maintenance 9 scheduling</div>;
export const maintenance_detail_10 = (p:any)=> <div>maintenance 10 spare parts</div>;
export const maintenance_detail_11 = (p:any)=> <div>maintenance 11 MRO</div>;
export const maintenance_detail_12 = (p:any)=> <div>maintenance 12 work order</div>;
export const maintenance_detail_13 = (p:any)=> <div>maintenance 13 scheduling</div>;
export const maintenance_detail_14 = (p:any)=> <div>maintenance 14 spare parts</div>;
export const maintenance_detail_15 = (p:any)=> <div>maintenance 15 MRO</div>;
export const maintenance_detail_16 = (p:any)=> <div>maintenance 16 work order</div>;
export const maintenance_detail_17 = (p:any)=> <div>maintenance 17 scheduling</div>;
export const maintenance_detail_18 = (p:any)=> <div>maintenance 18 spare parts</div>;
export const maintenance_detail_19 = (p:any)=> <div>maintenance 19 MRO</div>;